<Project>

  <PropertyGroup>
    <Authors>Rainer Erismann</Authors>
    <Version>0.9.3</Version>
    <FileVersion>0.9.3</FileVersion>
    <AssemblyVersion>0.9.3</AssemblyVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <DefineConstants>$(DefineConstants);JETBRAINS_ANNOTATIONS</DefineConstants>
    <!-- NuGet -->
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageProjectUrl>https://github.com/Reris/UBehave</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <!-- Test projects -->
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <!-- /Test projects -->

</Project>
