<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Product>NuBehave</Product>
    <Title>NuBehave is a Micro-Testhelper for BDD test scenarios.</Title>
    <Description>NuBehave is a Micro-Testhelper for BDD test scenarios to allow Gherkin or any other custom prose language in NUnit.</Description>
    <PackageTags>NUnit BDD UBehave xBehave Gherkin ATDD</PackageTags>
    <PackageIcon>UBehave-128.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="UBehave-128.png" Pack="true" PackagePath=""/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.5.0" />
  </ItemGroup>

</Project>
